server:
  port: 8820

spring:
  application:
    name: NBIoTResolution
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nbiot?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  type-aliases-package: org.spring.springboot.domain
  type-handlers-package: com.tjlcast.server.typeHandler

redis:
  host: localhost # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
   jedis:
     pool:
       max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
       max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-idle: 8 # 连接池中的最大空闲连接
       min-idle: 0 # 连接池中的最小空闲连接
   timeout: 3000ms # 连接超时时间（毫秒）
